/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData badger = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bear = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cow = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deer = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fox = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horse = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rabbit = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swain = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaver = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData incident = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
